#!/bin/sh

# 現在のブランチを取得
current_branch=$(git rev-parse --abbrev-ref HEAD)

# developブランチへのコミットを禁止
if [ "$current_branch" = "develop" ]; then
  echo "You are on the develop branch. Commits are not allowed on this branch."
  exit 1
fi

# pytestを実行して、テストが失敗した場合はコミットを禁止
echo "Running pytest..."
# pytestを実行
pytest
# pytestの終了ステータスをチェック
if [ $? -ne 0 ]; then
  echo "Tests failed. Commit aborted."
  exit 1
fi

exit 0